build:
  build:
    when:
      event: push
    image: 1and1internet/template-library-tools:giraffe
    auth_config:
      username: $$DOCKERHUB_USERNAME
      password: $$DOCKERHUB_PASSWORD
      email: $$DOCKERHUB_EMAIL
    privileged: true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    commands:
      - python3 /scripts/images/build.py
  spectests:
    when:
     event: push
    image: rzarouali/alpine-serverspec
    privileged: true
    volumes:
     - /var/run/docker.sock:/var/run/docker.sock
    commands:
     - export IMAGE=dronejob$CI_JOB_ID/${CI_REPO#*/}
     - echo $IMAGE
     - rspec tests/serverspec.rb

  publish:
    when:
      branch: master
      event: push
    image: 1and1internet/template-library-tools:giraffe
    auth_config:
     username: $$DOCKERHUB_USERNAME
     password: $$DOCKERHUB_PASSWORD
     email: $$DOCKERHUB_EMAIL
    privileged: true
    volumes:
     - /var/run/docker.sock:/var/run/docker.sock
    environment:
     - DOCKERHUB_USERNAME=$$DOCKERHUB_USERNAME
     - DOCKERHUB_EMAIL=$$DOCKERHUB_EMAIL
     - DOCKERHUB_PASSWORD=$$DOCKERHUB_PASSWORD
     - DEPENDENCY_GRAPH_URL=$$DEPENDENCY_GRAPH_URL
     - BUILD_TRIGGER_API_URL=$$BUILD_TRIGGER_API_URL
     - BUILD_TRIGGER_API_USERNAME=$$BUILD_TRIGGER_API_USERNAME
     - BUILD_TRIGGER_API_PASSWORD=$$BUILD_TRIGGER_API_PASSWORD
    commands:
     - python3 /scripts/images/publish.py
